CREATE TABLE IF NOT EXISTS "APP_USER" ( id BIGINT PRIMARY KEY, username VARCHAR(255) );
CREATE TABLE IF NOT EXISTS ADDRESS_ENTRY ( id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255), phone VARCHAR(255), email VARCHAR(255), street VARCHAR(255), user_id BIGINT, CONSTRAINT FK_USER FOREIGN KEY (user_id) REFERENCES "APP_USER"(id) );
INSERT INTO "APP_USER" (id, username) VALUES (1, 'user1');
INSERT INTO "APP_USER" (id, username) VALUES (2, 'user2');
INSERT INTO "APP_USER" (id, username) VALUES (3, 'user3');
INSERT INTO "APP_USER" (id, username) VALUES (4, 'user4');
INSERT INTO "APP_USER" (id, username) VALUES (5, 'user5');